version: "2"
services:
  node-app: 
    build: 
       context: .
       dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    ports:
      - 3000:3000
 

